# if you want to configure triggers for Azure CI see
# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#tags

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one line script'
 
# Install Node dependencies
- script: 
    echo Add other task to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install -g lambdatest-cypress-cli'
    
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 
      #!/bin/bash
      
      lambdatest-cypress run
